"""Freeze corpus inputs, schedule reports, and publish a final index."""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path
from urllib.parse import unquote, urlparse
from urllib.request import url2pathname

from apb_studio.corpus.discovery import (
    SNAKEFILE,
    workflow_implementation_paths,
    workflow_path,
)
from apb_studio.corpus.models import (
    CorpusIndex,
    Dataset,
    DatasetReport,
    ExecutionSettings,
    ReportLink,
    RunManifest,
    write_record,
)
from apb_studio.corpus.tables import (
    CORPUS_COLUMNS,
    INPUT_METADATA_COLUMNS,
    join_input_metadata,
    load_corpus,
    resolve_file,
    write_rows,
)
from apb_studio.disk import atomic_write_text


def dataset_alias(row: Dataset) -> str:
    """Keep the established software/hash aliases used by named routine selections."""
    software = re.sub(r"[^a-z0-9]", "", row.software_name.lower())
    return f"{software}-{Path(row.input_file).parent.name[:8]}"


def _named_datasets(rows: list[Dataset], selection: Path) -> list[Dataset]:
    names = {line.split("#", 1)[0].strip() for line in selection.read_text().splitlines()}
    names.discard("")
    selected, matched = [], set[str]()
    for row in rows:
        alias = dataset_alias(row)
        candidates = {
            row.input_file,
            alias,
            f"{row.module}/{alias}",
            f"{Path(row.input_file).parent.parent.name}/{alias}",
        }
        if names & candidates:
            selected.append(row)
            matched |= names & candidates
    if names - matched:
        raise ValueError(f"Unknown selected datasets: {sorted(names - matched)}")
    return selected


def select_datasets(rows: list[Dataset], selection: Path | None, limit: int) -> list[Dataset]:
    """Select named inputs, then an optional deterministic sample spread across software."""
    selected = _named_datasets(rows, selection) if selection is not None else rows
    if limit < 0:
        raise ValueError("fixtures must be nonnegative")
    if limit:
        groups: dict[str, list[Dataset]] = {}
        for row in selected:
            groups.setdefault(row.software_name, []).append(row)
        sampled: list[Dataset] = []
        while groups and len(sampled) < limit:
            for software in sorted(groups):
                sampled.append(groups[software].pop(0))
                if not groups[software]:
                    del groups[software]
                if len(sampled) == limit:
                    break
        selected = sampled
    if not selected:
        raise ValueError("No corpus datasets selected")
    return selected


def _file_digest(path: Path) -> bytes:
    """Hash a file with bounded peak memory."""
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while chunk := stream.read(1024 * 1024):
            digest.update(chunk)
    return digest.digest()


def _distribution_info_path(executable: Path, distribution: str) -> Path | None:
    """Find distribution metadata beside a Python entry-point without importing it."""
    prefix = executable.resolve().parent.parent
    site_packages = [
        *sorted((prefix / "lib").glob("python*/site-packages")),
        prefix / "Lib" / "site-packages",
    ]
    expected = re.sub(r"[-_.]+", "_", distribution).lower()
    for directory in site_packages:
        for candidate in sorted(directory.glob("*.dist-info")):
            name, separator, _version = candidate.name.removesuffix(".dist-info").rpartition("-")
            if separator and re.sub(r"[-_.]+", "_", name).lower() == expected:
                return candidate
    return None


def _editable_package_root(dist_info: Path, distribution: str) -> Path | None:
    """Resolve an editable distribution's source package from PEP 610 metadata."""
    direct_url = dist_info / "direct_url.json"
    try:
        payload = json.loads(direct_url.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if payload.get("dir_info", {}).get("editable") is not True:
        return None
    parsed = urlparse(str(payload.get("url", "")))
    if parsed.scheme != "file" or parsed.netloc:
        return None
    project_root = Path(url2pathname(unquote(parsed.path)))
    package_name = re.sub(r"[-.]+", "_", distribution)
    for candidate in (project_root / "src" / package_name, project_root / package_name):
        if candidate.is_dir():
            return candidate.resolve()
    return None


def _implementation_files(root: Path) -> tuple[Path, ...]:
    """List package-owned source and resources while excluding generated bytecode."""
    return tuple(
        path
        for path in sorted(root.rglob("*"))
        if path.is_file()
        and "__pycache__" not in path.parts
        and path.suffix not in {".pyc", ".pyo"}
    )


def _tool_identity(executable: Path, distribution: str, version: str) -> str:
    """Hash the launcher, metadata, and editable package tree for one tool."""
    digest = hashlib.sha256()
    digest.update(str(executable.resolve()).encode())
    digest.update(version.encode())
    digest.update(_file_digest(executable))
    dist_info = _distribution_info_path(executable, distribution)
    if dist_info is None:
        return digest.hexdigest()
    for name in ("METADATA", "RECORD", "direct_url.json"):
        metadata = dist_info / name
        if metadata.is_file():
            digest.update(name.encode())
            digest.update(_file_digest(metadata))
    package_root = _editable_package_root(dist_info, distribution)
    if package_root is not None:
        for path in _implementation_files(package_root):
            digest.update(path.relative_to(package_root).as_posix().encode())
            digest.update(_file_digest(path))
    return digest.hexdigest()


def _fingerprint(
    rows: Sequence[Dataset],
    data_root: Path,
    files: Sequence[Path],
    implementation_identities: Sequence[str],
) -> str:
    digest = hashlib.sha256()
    digest.update(str(data_root).encode())
    for identity in implementation_identities:
        digest.update(identity.encode())
    for row in rows:
        digest.update(row.model_dump_json().encode())
        for value in (row.input_file, row.vendor_parameter_file):
            path = resolve_file(data_root, value)
            if path.is_file():
                stat = path.stat()
                digest.update(f"{stat.st_size}:{stat.st_mtime_ns}".encode())
            else:
                digest.update(b"missing")
    for file in files:
        digest.update(str(file.resolve()).encode())
        digest.update(_file_digest(file))
    return digest.hexdigest()[:16]


def _tool_version(executable: Path) -> str:
    """Read one command-line tool version for the immutable run manifest."""
    return subprocess.run(
        [str(executable), "--version"],
        capture_output=True,
        text=True,
        check=True,
        timeout=30,
    ).stdout.strip()


def save_execution_settings(root: Path, settings: ExecutionSettings) -> tuple[str, Path]:
    """Publish reusable settings and a CSV preview without creating or executing a run."""
    settings_id = hashlib.sha256(settings.model_dump_json().encode()).hexdigest()[:16]
    directory = root / "settings" / settings_id
    atomic_write_text(directory / "corpus.csv", settings.corpus.read_text())
    if settings.downloads is not None:
        metadata = join_input_metadata(load_corpus(settings.corpus), settings.downloads)
        write_rows(
            directory / "input_metadata.csv",
            INPUT_METADATA_COLUMNS,
            [
                {
                    "input_file": item.input_file,
                    "input_file_size_bytes": str(item.input_file_size_bytes),
                }
                for item in metadata
            ],
        )
    if settings.workflow_table is not None:
        atomic_write_text(
            directory / settings.workflow_table.name, settings.workflow_table.read_text()
        )
    path = directory / "execution_settings.json"
    write_record(path, settings)
    return settings_id, path


def prepare_run(
    rows: list[Dataset],
    *,
    output_root: Path,
    settings: ExecutionSettings,
) -> tuple[Path, RunManifest]:
    """Snapshot readable CSVs and source before scheduling; reuse identical experiments."""
    source = workflow_path(settings.workflow)
    files = [
        SNAKEFILE,
        settings.corpus,
        *sorted(Path(__file__).parent.rglob("*.py")),
        *workflow_implementation_paths(settings.workflow),
    ]
    if settings.workflow_table is not None:
        files.append(settings.workflow_table)
    if settings.downloads is not None:
        files.append(settings.downloads)
    # Each declared tool name is also its distribution name, so identity needs no tool table.
    tools = dict(sorted(settings.tools.items()))
    tool_versions = {tool: _tool_version(path) for tool, path in tools.items()}
    implementation_identities = [
        _tool_identity(path, tool, tool_versions[tool]) for tool, path in tools.items()
    ]
    settings_id, _ = save_execution_settings(output_root.resolve() / "corpus", settings)
    implementation_identities.append(settings_id)
    fingerprint = _fingerprint(
        rows,
        settings.data_root,
        files,
        implementation_identities,
    )
    run_id = f"{settings.workflow}-{settings.format}-{fingerprint}"
    root = output_root.resolve() / "corpus" / run_id
    root.mkdir(parents=True, exist_ok=True)
    manifest_path = root / "run.json"
    if manifest_path.is_file():
        return root, RunManifest.model_validate_json(manifest_path.read_text())
    write_rows(root / "selected_corpus.csv", CORPUS_COLUMNS, [row.model_dump() for row in rows])
    metadata_file: str | None = None
    if settings.downloads is not None:
        metadata = join_input_metadata(rows, settings.downloads)
        metadata_file = "input_metadata.csv"
        write_rows(
            root / metadata_file,
            INPUT_METADATA_COLUMNS,
            [
                {
                    "input_file": item.input_file,
                    "input_file_size_bytes": str(item.input_file_size_bytes),
                }
                for item in metadata
            ],
        )
    atomic_write_text(root / "corpus.csv", settings.corpus.read_text())
    write_record(root / "execution_settings.json", settings)
    atomic_write_text(root / source.name, source.read_text())
    if settings.workflow_table is not None:
        atomic_write_text(root / settings.workflow_table.name, settings.workflow_table.read_text())
    links = []
    for row in rows:
        key = hashlib.sha256(row.input_file.encode()).hexdigest()[:16]
        links.append(
            ReportLink(
                input_file=row.input_file,
                path=f"reports/{key}.json",
                progress=f"reports/{key}.progress.json",
                output_dir=f"artifacts/{key}",
            )
        )
    manifest = RunManifest(
        run_id=run_id,
        workflow=settings.workflow,
        format=settings.format,
        data_root=settings.data_root,
        tools=tools,
        tool_versions=tool_versions,
        cores=settings.cores,
        corpus="selected_corpus.csv",
        source_corpus="corpus.csv",
        input_metadata=metadata_file,
        settings_id=settings_id,
        execution_settings="execution_settings.json",
        workflow_source=source.name,
        workflow_table=settings.workflow_table.name
        if settings.workflow_table is not None
        else None,
        reports=links,
    )
    write_record(manifest_path, manifest)
    return root, manifest


def publish_catalog(root: Path) -> None:
    """Publish only runs linked to a saved, inspectable execution configuration."""
    manifests = sorted(
        (path for path in root.glob("*/run.json") if _has_execution_settings(root, path)),
        key=lambda path: path.stat().st_mtime_ns,
        reverse=True,
    )
    payload = {
        "schema_version": 1,
        "runs": [str(path.relative_to(root)) for path in manifests],
        "settings": [
            str(path.relative_to(root))
            for path in sorted((root / "settings").glob("*/execution_settings.json"))
        ],
    }
    atomic_write_text(root / "index.json", json.dumps(payload, indent=2) + "\n")


def _has_execution_settings(root: Path, manifest: Path) -> bool:
    payload = json.loads(manifest.read_text())
    settings_id = payload.get("settings_id")
    return (
        isinstance(settings_id, str)
        and re.fullmatch(r"[0-9a-f]{16}", settings_id) is not None
        and (root / "settings" / settings_id / "execution_settings.json").is_file()
    )


def command_for(root: Path, manifest: RunManifest, link: ReportLink) -> list[str]:
    """Build the identical workflow CLI for every dataset without stage knowledge."""
    command = [
        sys.executable,
        "-m",
        f"apb_studio.workflows.workflow_{manifest.workflow}",
        "--corpus",
        str(root / manifest.corpus),
        "--data-root",
        str(manifest.data_root),
        "--input-file",
        link.input_file,
        "--format",
        manifest.format,
        "--output-dir",
        str(root / link.output_dir),
        "--report",
        str(root / link.path),
        "--run-id",
        manifest.run_id,
    ]
    for tool, path in sorted(manifest.tools.items()):
        command.extend(["--tool", f"{tool}={path}"])
    if manifest.workflow_table is not None:
        command.extend(["--workflow-table", str(root / manifest.workflow_table)])
    return command


def publish_index(root: Path, manifest: RunManifest) -> None:
    """Validate every final report, including failed APB results, before publishing the index."""
    for link in manifest.reports:
        report = DatasetReport.model_validate_json((root / link.path).read_text())
        if (
            report.run_id != manifest.run_id
            or report.workflow != manifest.workflow
            or report.format != manifest.format
            or report.dataset.input_file != link.input_file
            or report.status not in {"succeeded", "failed"}
            or any(step.status in {"pending", "running"} for step in report.steps)
        ):
            raise ValueError(f"Mismatched or unfinished dataset report: {link.path}")
    write_record(
        root / "corpus_index.json",
        CorpusIndex(
            run_id=manifest.run_id,
            workflow=manifest.workflow,
            format=manifest.format,
            reports=manifest.reports,
        ),
    )
