"""Registry-driven target expansion and corpus progress state.

APB's parsing-rule JSONs decide which conversion branches an input supports. This module expands
each discovered branch through the registry's stage DAG, producing the concrete paths and commands
shared by Snakemake and the dashboard.
"""

from __future__ import annotations

import csv
import json
import math
import re
import shlex
from collections import defaultdict
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from anndata_proteomics.converters import pipeline as conversion_pipeline

from apb_studio import capabilities
from apb_studio.registry import load_registry  # noqa: F401 (re-exported for callers)

MUDATA = conversion_pipeline.MUDATA
LEVELS = tuple(conversion_pipeline.LEVELS)
BRANCHES = (MUDATA, *LEVELS)
CapabilityResolver = Callable[[Path, Path, str], capabilities.CapabilityDiscovery]

# The basket a dataset sits in before any stage has run (the DAG source). Kept here so the
# dashboard and baskets() agree on the label without hardcoding it in the GUI.
INPUTS_BASKET = "inputs"

# Wildcard-constraint regexes the Snakefile uses to route one `{artifact}` wildcard to the right
# stage rule (the four are disjoint, so there is no ambiguity).
_LEVEL_RE = "|".join(LEVELS)
CONVERT_ARTIFACT_RE = rf"{MUDATA}\.h5mu|(?:{_LEVEL_RE})\.h5ad"
ANNOTATE_ARTIFACT_RE = rf"{MUDATA}\.annotated\.h5mu|(?:{_LEVEL_RE})\.annotated\.h5ad"
FASTA_ARTIFACT_RE = (
    rf"{MUDATA}\.fasta\.h5mu|"
    rf"(?:{_LEVEL_RE})\.fasta\.h5ad"
)
PROTEOBENCH_ARTIFACT_RE = rf"{MUDATA}\.proteobench\.h5mu|(?:{_LEVEL_RE})\.proteobench\.h5ad"

_PLACEHOLDER = re.compile(r"\{(\w+)\}")


class CleanGuardError(Exception):
    """Raised when a Clean would delete a path under `input_root` — never an input (§8.3)."""


@dataclass(frozen=True)
class Target:
    """One ``(module, dataset, branch, stage)`` unit of work."""

    module: str
    dataset: str
    stage: str  # registry stage name
    output: Path  # absolute, under output_root
    command: list[str]  # fully-rendered argv (ready for shell / preview)
    inputs: list[Path] = field(default_factory=list)
    vendor: str = ""
    level: str | None = None
    branch: str = MUDATA
    blocked_reason: str | None = None


@dataclass(frozen=True, slots=True)
class ResolvedFixture:
    """One complete local fixture resolved against APB's parsing rules."""

    module: str
    repo_name: str
    intermediate_hash: str
    dataset: str
    software: str
    vendor: str
    input_path: Path
    parameter_path: Path
    branches: tuple[str, ...]
    capability_status: str
    diagnostic: str | None = None
    annotation_path: Path | None = None
    fasta_path: Path | None = None
    annotation_error: str | None = None
    fasta_error: str | None = None
    module_settings_error: str | None = None
    parameter_vendor: str = ""

    @property
    def identity(self) -> tuple[str, str, str]:
        """Return the stable fixture identity used by the output-alias store."""
        return self.module, self.repo_name, self.intermediate_hash


@dataclass(frozen=True, slots=True)
class RunSnapshot:
    """Immutable execution input generated by Corpus Runner for one launch."""

    schema_version: int
    run_id: str
    created_at: str
    test_data_root: Path
    output_root: Path
    registry_digest: str
    apb_version: str | None
    fixtures: tuple[ResolvedFixture, ...]
    targets: tuple[Target, ...]


RUN_SNAPSHOT_SCHEMA_VERSION = 1


def run_snapshot_data(snapshot: RunSnapshot) -> dict[str, Any]:
    """Return the JSON-compatible representation of one generated run."""
    return {
        "schema_version": snapshot.schema_version,
        "run_id": snapshot.run_id,
        "created_at": snapshot.created_at,
        "test_data_root": str(snapshot.test_data_root),
        "output_root": str(snapshot.output_root),
        "registry_digest": snapshot.registry_digest,
        "apb_version": snapshot.apb_version,
        "fixtures": [
            {
                "module": fixture.module,
                "repo_name": fixture.repo_name,
                "intermediate_hash": fixture.intermediate_hash,
                "dataset": fixture.dataset,
                "software": fixture.software,
                "vendor": fixture.vendor,
                "parameter_vendor": fixture.parameter_vendor,
                "input_path": str(fixture.input_path),
                "parameter_path": str(fixture.parameter_path),
                "branches": list(fixture.branches),
                "capability_status": fixture.capability_status,
                "diagnostic": fixture.diagnostic,
                "annotation_path": (
                    str(fixture.annotation_path) if fixture.annotation_path is not None else None
                ),
                "fasta_path": (str(fixture.fasta_path) if fixture.fasta_path is not None else None),
                "annotation_error": fixture.annotation_error,
                "fasta_error": fixture.fasta_error,
                "module_settings_error": fixture.module_settings_error,
            }
            for fixture in snapshot.fixtures
        ],
        "targets": [
            {
                "module": target.module,
                "dataset": target.dataset,
                "stage": target.stage,
                "output": str(target.output),
                "command": list(target.command),
                "inputs": [str(path) for path in target.inputs],
                "vendor": target.vendor,
                "level": target.level,
                "branch": target.branch,
                "blocked_reason": target.blocked_reason,
            }
            for target in snapshot.targets
        ],
    }


def run_snapshot_from_data(data: dict[str, Any]) -> RunSnapshot:
    """Validate and decode a generated run JSON object."""
    version = data.get("schema_version")
    if version != RUN_SNAPSHOT_SCHEMA_VERSION:
        raise ValueError(
            "Unsupported run snapshot schema version "
            f"{version!r}; expected {RUN_SNAPSHOT_SCHEMA_VERSION}."
        )
    fixtures = tuple(
        ResolvedFixture(
            module=str(item["module"]),
            repo_name=str(item["repo_name"]),
            intermediate_hash=str(item["intermediate_hash"]),
            dataset=str(item["dataset"]),
            software=str(item["software"]),
            vendor=str(item["vendor"]),
            input_path=Path(item["input_path"]),
            parameter_path=Path(item["parameter_path"]),
            branches=tuple(str(branch) for branch in item.get("branches", [])),
            capability_status=str(item["capability_status"]),
            diagnostic=(str(item["diagnostic"]) if item.get("diagnostic") is not None else None),
            annotation_path=(
                Path(item["annotation_path"]) if item.get("annotation_path") is not None else None
            ),
            fasta_path=(Path(item["fasta_path"]) if item.get("fasta_path") is not None else None),
            annotation_error=(
                str(item["annotation_error"]) if item.get("annotation_error") is not None else None
            ),
            fasta_error=(str(item["fasta_error"]) if item.get("fasta_error") is not None else None),
            module_settings_error=(
                str(item["module_settings_error"])
                if item.get("module_settings_error") is not None
                else None
            ),
            parameter_vendor=str(item.get("parameter_vendor", item["vendor"])),
        )
        for item in data.get("fixtures", [])
    )
    targets = tuple(
        Target(
            module=str(item["module"]),
            dataset=str(item["dataset"]),
            stage=str(item["stage"]),
            output=Path(item["output"]),
            command=[str(token) for token in item.get("command", [])],
            inputs=[Path(path) for path in item.get("inputs", [])],
            vendor=str(item.get("vendor", "")),
            level=str(item["level"]) if item.get("level") is not None else None,
            branch=str(item.get("branch", MUDATA)),
            blocked_reason=(
                str(item["blocked_reason"]) if item.get("blocked_reason") is not None else None
            ),
        )
        for item in data.get("targets", [])
    )
    snapshot = RunSnapshot(
        schema_version=RUN_SNAPSHOT_SCHEMA_VERSION,
        run_id=str(data["run_id"]),
        created_at=str(data["created_at"]),
        test_data_root=Path(data["test_data_root"]),
        output_root=Path(data["output_root"]),
        registry_digest=str(data["registry_digest"]),
        apb_version=(str(data["apb_version"]) if data.get("apb_version") is not None else None),
        fixtures=fixtures,
        targets=targets,
    )
    _validate_snapshot_paths(snapshot)
    return snapshot


def _validate_snapshot_paths(snapshot: RunSnapshot) -> None:
    """Reject malformed snapshots whose outputs escape the frozen output root."""
    output_root = snapshot.output_root.resolve()
    for target in snapshot.targets:
        output = target.output.resolve()
        if output_root != output and output_root not in output.parents:
            raise ValueError(
                f"Run target {target.output} is outside output root {snapshot.output_root}."
            )


def write_run_snapshot(snapshot: RunSnapshot, path: Path | str) -> Path:
    """Create one run JSON exactly once and return its path."""
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("x", encoding="utf-8") as stream:
        json.dump(run_snapshot_data(snapshot), stream, indent=2)
        stream.write("\n")
    return destination


def load_run_snapshot(path: Path | str) -> RunSnapshot:
    """Load and validate a Corpus Runner-generated run JSON file."""
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Run snapshot must contain one JSON object.")
    return run_snapshot_from_data(data)


def convert_artifact(branch: str) -> str:
    """Return the converted artifact name for a discovered branch."""
    if branch not in BRANCHES:
        raise ValueError(f"unknown conversion branch {branch!r}; expected one of {BRANCHES}")
    return f"{branch}{convert_suffix(branch)}"


def convert_suffix(branch: str) -> str:
    """Return ``.h5mu`` for MuData and ``.h5ad`` for standalone levels."""
    return ".h5mu" if branch == MUDATA else ".h5ad"


def stage_artifact(stage: dict[str, Any], branch: str) -> str:
    """Return the branch-qualified artifact name produced by one stage."""
    if not stage.get("depends_on"):
        return convert_artifact(branch)
    return f"{branch}.{stage['artifact']}{convert_suffix(branch)}"


def validate_dataset(module: str, dataset_cfg: dict[str, Any]) -> None:
    """Validate the corpus-manifest fields needed for capability discovery."""
    name = dataset_cfg.get("name", "?")
    for field_name in ("name", "vendor", "input", "params"):
        if not dataset_cfg.get(field_name):
            raise ValueError(f"{module}/{name}: missing required {field_name!r}")


def render_command(template: str, ctx: dict[str, Any]) -> list[str]:
    """Substitute `{placeholder}`s in a registry command template → an argv list.

    Plain per-token substitution (so a value with spaces stays one argv element); raises on any
    unfilled `{placeholder}`. There is no optional-group grammar — `--level` is appended by
    `expand_targets`, not encoded in the template (§7.2).
    """
    missing = sorted({m.group(1) for m in _PLACEHOLDER.finditer(template)} - set(ctx))
    if missing:
        raise KeyError(f"unfilled placeholder(s) {missing} in command template {template!r}")
    return [_PLACEHOLDER.sub(lambda m: str(ctx[m.group(1)]), token) for token in template.split()]


# --- stage-graph helpers (topology is data — decision 5 / §13) --------------------------------


def stage_order(registry: list[dict[str, Any]]) -> list[str]:
    """Derive topological stage order from `depends_on`, never a hardcoded list (§13.3)."""
    deps = {s["name"]: list(s.get("depends_on") or []) for s in registry}
    order: list[str] = []
    seen: set[str] = set()

    def visit(name: str) -> None:
        if name in seen:
            return
        seen.add(name)
        for dep in deps.get(name, []):
            visit(dep)
        order.append(name)

    for stage in registry:
        visit(stage["name"])
    return order


def basket_label(stage: dict[str, Any]) -> str:
    """The kanban basket a dataset reaches after this stage (the registry `basket` field)."""
    return stage.get("basket", stage["name"])


def basket_names(registry: list[dict[str, Any]]) -> list[str]:
    """Order flow-strip basket labels as inputs, then one per stage (§8.3)."""
    by_name = {s["name"]: s for s in registry}
    return [INPUTS_BASKET] + [basket_label(by_name[name]) for name in stage_order(registry)]


def stage_by_basket(registry: list[dict[str, Any]]) -> dict[str, str]:
    """Map each non-`inputs` basket label back to the stage that defines it (for Clean, §8.3)."""
    return {basket_label(s): s["name"] for s in registry}


def descendants(registry: list[dict[str, Any]], stage: str) -> set[str]:
    """Return stages that transitively depend on ``stage`` in the registry DAG."""
    children: dict[str, set[str]] = defaultdict(set)
    for s in registry:
        for dep in s.get("depends_on") or []:
            children[dep].add(s["name"])
    out: set[str] = set()
    stack = [stage]
    while stack:
        for child in children.get(stack.pop(), ()):
            if child not in out:
                out.add(child)
                stack.append(child)
    return out


def _resolve(value: str, base: Path) -> Path:
    """Resolve a config path: absolute as-is, else relative to `base`."""
    p = Path(value)
    return p if p.is_absolute() else base / p


def _resource_names(stage: dict[str, Any]) -> tuple[str, ...]:
    """Return a stage's optional resource placeholder."""
    resource = stage.get("resource")
    return (resource,) if resource is not None else ()


def _resolved_resource(
    fixture: ResolvedFixture,
    name: str,
) -> tuple[Path | None, str | None]:
    """Resolve a registry resource name against one frozen fixture."""
    if name == "module_settings":
        return fixture.annotation_path, fixture.module_settings_error
    return (
        getattr(fixture, f"{name}_path", None),
        getattr(fixture, f"{name}_error", None),
    )


def _nearest_upstream(
    deps: list[str],
    emitted: dict[str, Path],
    reg: dict[str, dict[str, Any]],
) -> Path:
    """Nearest already-emitted upstream artifact for a stage's `depends_on` (§13.1 reconnection).

    Walk the `depends_on` graph until an emitted stage is found, so an optional *intermediate* stage
    that was skipped for this dataset is transparent — its successor reconnects to the last present
    artifact. The DAG root always emits, so a well-formed registry always yields one.
    """
    found = _emitted_ancestor(deps, emitted, reg)
    if found is None:
        raise ValueError(f"No emitted upstream stage for dependencies {deps}.")
    return found


def _emitted_ancestor(
    deps: list[str],
    emitted: dict[str, Path],
    reg: dict[str, dict[str, Any]],
) -> Path | None:
    """Walk `depends_on` breadth-first for the first emitted artifact."""
    for dep in deps:
        if dep in emitted:
            return emitted[dep]
    for dep in deps:
        up = _emitted_ancestor(list(reg.get(dep, {}).get("depends_on") or []), emitted, reg)
        if up is not None:
            return up
    return None


def discover_dataset_branches(
    dataset_cfg: dict[str, Any],
    input_root: Path,
    *,
    discover: CapabilityResolver = capabilities.discover_capabilities,
) -> capabilities.CapabilityDiscovery:
    """Resolve one dataset's APB branches from its input, parameters, and parsing JSONs."""
    return discover(
        _resolve(dataset_cfg["input"], input_root),
        _resolve(dataset_cfg["params"], input_root),
        dataset_cfg["vendor"],
    )


def expand_targets(  # noqa: C901, PLR0912 - registry-driven target graph expansion
    registry: list[dict[str, Any]],
    corpus: dict[str, Any],
    output_root: Path | str | None = None,
    input_root: Path | str | None = None,
    *,
    discover: CapabilityResolver = capabilities.discover_capabilities,
) -> list[Target]:
    """Expand the corpus's JSON-supported branches through the registry stage DAG."""
    reg = {s["name"]: s for s in registry}
    order = stage_order(registry)
    out_root = Path(output_root if output_root is not None else corpus["output_root"])
    in_root = Path(input_root if input_root is not None else corpus["input_root"])

    targets: list[Target] = []
    for module, mcfg in corpus["modules"].items():
        for ds in mcfg["datasets"]:
            validate_dataset(module, ds)
            discovery = discover_dataset_branches(ds, in_root, discover=discover)
            for branch in discovery.branches:
                base = out_root / module / ds["name"]
                emitted: dict[str, Path] = {}

                for name in order:
                    stage = reg[name]
                    deps = list(stage.get("depends_on") or [])

                    if not deps:
                        output = base / stage_artifact(stage, branch)
                        command = render_command(
                            stage["command"],
                            {
                                "input": _resolve(ds["input"], in_root),
                                "output": output.with_suffix(""),
                                "vendor": ds["vendor"],
                                "parameter_vendor": (
                                    discovery.parameter_software_slug or ds["vendor"]
                                ),
                                "params": _resolve(ds["params"], in_root),
                            },
                        )
                        if branch != MUDATA:
                            command += ["--level", branch]
                        inputs = [
                            _resolve(ds["input"], in_root),
                            _resolve(ds["params"], in_root),
                        ]
                    else:
                        resource_paths: dict[str, Path] = {}
                        missing_resource = False
                        for resource in _resource_names(stage):
                            config_name = (
                                "annotation" if resource == "module_settings" else resource
                            )
                            raw_resource = mcfg.get(config_name)
                            if raw_resource is None:
                                missing_resource = True
                                break
                            resource_paths[resource] = _resolve(raw_resource, in_root)
                        if missing_resource:
                            continue

                        # A required missing stage blocks its descendants. Only explicitly optional
                        # intermediate stages may reconnect to the nearest emitted ancestor.
                        required_missing = any(
                            dep not in emitted and not reg.get(dep, {}).get("optional")
                            for dep in deps
                        )
                        if required_missing:
                            continue
                        upstream = _nearest_upstream(deps, emitted, reg)
                        output = base / stage_artifact(stage, branch)
                        context = {"input": upstream, "output": output}
                        context.update(resource_paths)
                        command = render_command(stage["command"], context)
                        inputs = [upstream]
                        inputs.extend(resource_paths.values())

                    emitted[name] = output
                    targets.append(
                        Target(
                            module=module,
                            dataset=ds["name"],
                            stage=name,
                            output=output,
                            command=command,
                            inputs=inputs,
                            vendor=ds["vendor"],
                            level=None if branch == MUDATA else branch,
                            branch=branch,
                        )
                    )
    return targets


def expand_resolved_targets(  # noqa: C901, PLR0912 - registry-driven target graph expansion
    registry: list[dict[str, Any]],
    fixtures: tuple[ResolvedFixture, ...] | list[ResolvedFixture],
    output_root: Path | str,
) -> list[Target]:
    """Expand frozen fixture branches into concrete stage targets.

    Every stage receives a target, even when its own module resource is absent. Such a target
    carries ``blocked_reason`` and is excluded from Snakemake while its independent ancestors stay
    runnable. This preserves the complete branch topology needed for truthful status propagation.
    """
    reg = {stage["name"]: stage for stage in registry}
    order = stage_order(registry)
    out_root = Path(output_root)
    targets: list[Target] = []

    for fixture in fixtures:
        for branch in fixture.branches:
            base = out_root / fixture.repo_name / fixture.dataset
            emitted: dict[str, Path] = {}

            for name in order:
                stage = reg[name]
                dependencies = list(stage.get("depends_on") or [])
                blocked_reason: str | None = None

                if not dependencies:
                    output = base / stage_artifact(stage, branch)
                    command = render_command(
                        stage["command"],
                        {
                            "input": fixture.input_path,
                            "output": output.with_suffix(""),
                            "vendor": fixture.vendor,
                            "parameter_vendor": (fixture.parameter_vendor or fixture.vendor),
                            "params": fixture.parameter_path,
                        },
                    )
                    if branch != MUDATA:
                        command += ["--level", branch]
                    inputs = [fixture.input_path, fixture.parameter_path]
                else:
                    # Every stage emits a target here, so a dependency always has an artifact.
                    upstream = _nearest_upstream(dependencies, emitted, reg)
                    output = base / stage_artifact(stage, branch)
                    inputs = [upstream]
                    context: dict[str, Path] = {"input": upstream, "output": output}

                    for resource_name in _resource_names(stage):
                        resource_path, resource_error = _resolved_resource(
                            fixture,
                            resource_name,
                        )
                        if resource_error is not None:
                            blocked_reason = resource_error
                        elif resource_path is None:
                            blocked_reason = f"Missing module resource: {resource_name}"
                        else:
                            context[resource_name] = resource_path
                            inputs.append(resource_path)

                    command = (
                        render_command(stage["command"], context) if blocked_reason is None else []
                    )

                emitted[name] = output
                targets.append(
                    Target(
                        module=fixture.repo_name,
                        dataset=fixture.dataset,
                        stage=name,
                        output=output,
                        command=command,
                        inputs=inputs,
                        vendor=fixture.vendor,
                        level=None if branch == MUDATA else branch,
                        branch=branch,
                        blocked_reason=blocked_reason,
                    )
                )
    return targets


def coverage(targets: list[Target]) -> list[dict[str, Any]]:
    """One row per Target with `done = output.exists()` — filesystem-as-DB (decision 4)."""
    return [
        {
            "module": t.module,
            "dataset": t.dataset,
            "branch": t.branch,
            "stage": t.stage,
            "artifact": t.output.name,
            "done": t.output.exists(),
        }
        for t in targets
    ]


def target_blocker(
    target: Target,
    targets: list[Target],
    *,
    existing_artifacts_satisfy: bool = True,
) -> str | None:
    """Return the first missing external prerequisite in a target's upstream chain.

    ``existing_artifacts_satisfy`` is true for display state: a completed artifact is usable even
    when an old source has since disappeared. Snakemake target selection sets it false so every
    declared input chain is valid before asking Snakemake to assess timestamps.
    """
    by_output = {item.output: item for item in targets}
    memo: dict[Path, str | None] = {}

    def visit(item: Target) -> str | None:
        if item.output in memo:
            return memo[item.output]
        if existing_artifacts_satisfy and item.output.exists():
            memo[item.output] = None
            return None
        if item.blocked_reason is not None:
            memo[item.output] = item.blocked_reason
            return item.blocked_reason
        memo[item.output] = None
        for input_path in item.inputs:
            upstream = by_output.get(input_path)
            if upstream is not None:
                blocker = visit(upstream)
                if blocker is not None:
                    memo[item.output] = blocker
                    return blocker
            elif not input_path.exists():
                blocker = f"Missing prerequisite: {input_path}"
                memo[item.output] = blocker
                return blocker
        return None

    return visit(target)


def runnable_targets(targets: list[Target]) -> list[Target]:
    """Return targets Snakemake can safely assess, including existing outputs.

    Existing artifacts remain in the target set so Snakemake, rather than the dashboard, decides
    whether they are stale. Targets with any missing external prerequisite are excluded so one bad
    resource cannot prevent DAG construction for independent branches.
    """
    return [
        target
        for target in targets
        if target_blocker(
            target,
            targets,
            existing_artifacts_satisfy=False,
        )
        is None
    ]


def _log_error(logpath: Path) -> str | None:
    """The apb error summary from a per-rule log (Snakefile tees each rule to ``<artifact>.log``).

    Prefers the exception line (``ValueError: …`` / ``…Error: …``); else the last non-empty line.
    Used to surface *why* a convert/annotate/fasta failed when its artifact is absent.
    """
    try:
        lines = [
            ln.strip() for ln in logpath.read_text(errors="replace").splitlines() if ln.strip()
        ]
    except OSError:
        return None
    if not lines:
        return None
    for line in reversed(lines):
        if re.match(r"^[\w.]*(Error|Exception):", line):
            return line
    return lines[-1]


def failure_marker_path(output: Path | str) -> Path:
    """Return the marker written only after a rule command exits unsuccessfully."""
    return Path(f"{output}.failed")


def benchmark_path(output: Path | str) -> Path:
    """Return the Snakemake benchmark file adjacent to a stage artifact."""
    return Path(f"{output}.benchmark.tsv")


def _benchmark_seconds(output: Path | str) -> float | None:
    """Read one rule's elapsed seconds, tolerating old or partial metadata."""
    try:
        with benchmark_path(output).open(encoding="utf-8", newline="") as handle:
            row = next(csv.DictReader(handle, delimiter="\t"), None)
        seconds = float(row["s"]) if row is not None else math.nan
    except (OSError, KeyError, TypeError, ValueError):
        return None
    return seconds if math.isfinite(seconds) and seconds >= 0 else None


def format_duration(seconds: float) -> str:
    """Format elapsed seconds compactly for a stage cell."""
    if seconds < 10:
        return f"{seconds:.1f}s"
    total_seconds = round(seconds)
    if total_seconds < 60:
        return f"{total_seconds}s"
    minutes, remainder = divmod(total_seconds, 60)
    if minutes < 60:
        return f"{minutes}m {remainder:02d}s"
    hours, minutes = divmod(minutes, 60)
    return f"{hours}h {minutes:02d}m"


def _failed_rule_error(output: Path | str) -> str | None:
    """Return a rule failure only when its authoritative failure marker exists.

    A rule's ``tee`` log is created and populated while that rule is still running, so log
    existence alone cannot distinguish live progress from failure. The Snakefile clears this
    marker immediately before each attempt and writes it only after a non-zero command exit.
    """
    marker = failure_marker_path(output)
    if not marker.exists():
        return None
    error = _log_error(Path(f"{output}.log"))
    if error is not None:
        return error
    try:
        exit_status = marker.read_text(encoding="utf-8", errors="replace").strip()
    except OSError:
        exit_status = ""
    return f"Rule failed{f' ({exit_status})' if exit_status else ''}"


def _provenance_warnings(sidecar: Path) -> list[str]:
    """Return warning fields from an artifact provenance sidecar."""
    if not sidecar.exists():
        return []
    try:
        data = json.loads(sidecar.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    if not isinstance(data, dict):
        return []
    if data.get("warning"):
        return [f"{data.get('stage', 'artifact')}: {data['warning']}"]
    return []


def problems(  # noqa: C901 - diagnostic aggregation across target states
    corpus: dict[str, Any],
    targets: list[Target],
) -> dict[tuple[str, str], list[str]]:
    """Per-dataset problems to surface in the baskets (§8, review round 2).

    Two sources: **static** — declared files that don't exist (a dataset's `input`/`params`, or a
    module's `annotation:`/`fasta:` resource) — caught without running anything; and **runtime** —
    warnings apb recorded while still producing an artifact (e.g. an unparsable params file), read
    from each dataset's provenance.json. Keyed by (module, dataset); empty when a dataset is clean.
    """
    in_root = Path(corpus.get("input_root", ""))
    out: dict[tuple[str, str], list[str]] = defaultdict(list)
    for module, mcfg in corpus.get("modules", {}).items():
        ann, fasta = mcfg.get("annotation"), mcfg.get("fasta")
        ann_missing = ann is not None and not _resolve(ann, in_root).exists()
        fasta_missing = fasta is not None and not _resolve(fasta, in_root).exists()
        for ds in mcfg.get("datasets", []):
            key = (module, ds["name"])
            if ds.get("input") and not _resolve(ds["input"], in_root).exists():
                out[key].append(f"input file missing: {ds['input']}")
            if ds.get("params") and not _resolve(ds["params"], in_root).exists():
                out[key].append(f"params file missing: {ds['params']}")
            if ann_missing:
                out[key].append(f"annotation resource missing: {ann}")
            if fasta_missing:
                out[key].append(f"fasta missing: {fasta}")
    for target in targets:
        sidecar = Path(f"{target.output}.provenance.json")
        out[(target.module, target.dataset)].extend(_provenance_warnings(sidecar))
    # Runtime failures have an explicit marker written only after the rule command exits non-zero.
    # A growing tee log without that marker belongs to a rule that may still be running.
    for t in targets:
        if not t.output.exists():
            err = _failed_rule_error(t.output)
            if err:
                out[(t.module, t.dataset)].append(f"{t.stage} failed: {err}")
    return {k: v for k, v in out.items() if v}


def _terminal_blocker(  # noqa: C901 - recursive target-state evaluation
    target: Target,
    targets: list[Target],
) -> str | None:
    """Return a terminal upstream blocker, but never a direct or pending prerequisite."""
    by_output = {item.output: item for item in targets}
    memo: dict[Path, str | None] = {}

    def visit(item: Target) -> str | None:  # noqa: PLR0911 - target-state decision table
        if item.output in memo:
            return memo[item.output]
        if item.output.exists():
            memo[item.output] = None
            return None
        if item.blocked_reason is not None:
            memo[item.output] = item.blocked_reason
            return item.blocked_reason

        memo[item.output] = None
        for input_path in item.inputs:
            upstream = by_output.get(input_path)
            if upstream is None:
                continue
            if upstream.output.exists():
                continue
            upstream_error = _failed_rule_error(upstream.output)
            if upstream_error is not None:
                reason = f"Blocked by failed upstream stage {upstream.stage}: {upstream_error}"
                memo[item.output] = reason
                return reason
            upstream_blocker = visit(upstream)
            if upstream_blocker is not None:
                reason = f"Blocked by upstream stage {upstream.stage}: {upstream_blocker}"
                memo[item.output] = reason
                return reason
        return None

    return visit(target)


def _stage_detail(  # noqa: PLR0911 - explicit stage-state decision table
    target: Target | None,
    *,
    targets: list[Target],
    missing_reason: str | None = None,
) -> dict[str, str]:
    """Build one JSON-compatible table-cell detail payload."""
    if target is None:
        return {
            "state": "unsupported",
            "display": "UNSUPPORTED",
            "error": missing_reason or "Stage target unavailable",
        }

    artifact = str(target.output)
    log_path = str(Path(f"{target.output}.log"))
    base = {"artifact": artifact, "log": log_path}
    if target.command:
        base["command"] = shlex.join(target.command)
    if target.output.exists():
        duration_seconds = _benchmark_seconds(target.output)
        timing = (
            {}
            if duration_seconds is None
            else {
                "duration": format_duration(duration_seconds),
                "duration_seconds": str(duration_seconds),
            }
        )
        display = "DONE" if not timing else f"DONE · {timing['duration']}"
        return {**base, **timing, "state": "completed", "display": display}
    error = _failed_rule_error(target.output)
    if error is not None:
        return {**base, "state": "failed", "display": "FAILED", "error": error}
    if target.blocked_reason is not None:
        return {
            **base,
            "state": "unsupported",
            "display": "UNSUPPORTED",
            "error": target.blocked_reason,
        }
    target_outputs = {item.output for item in targets}
    missing_prerequisite = next(
        (
            input_path
            for input_path in target.inputs
            if input_path not in target_outputs and not input_path.exists()
        ),
        None,
    )
    if missing_prerequisite is not None:
        return {
            **base,
            "state": "unsupported",
            "display": "UNSUPPORTED",
            "error": f"Missing prerequisite: {missing_prerequisite}",
        }
    blocker = _terminal_blocker(target, targets)
    if blocker is not None:
        return {**base, "state": "unavailable", "display": ""}
    return {**base, "state": "pending", "display": ""}


def branch_rows(
    run: RunSnapshot | dict[str, Any],
    targets: list[Target],
    *,
    registry: list[dict[str, Any]] | None = None,
    discover: CapabilityResolver = capabilities.discover_capabilities,
) -> list[dict[str, Any]]:
    """Return one compact progress row per JSON-supported dataset branch."""
    registry = registry or load_registry()
    if isinstance(run, dict):
        run = _legacy_run_snapshot(registry, run, targets, discover=discover)

    order = stage_order(registry)
    by_key = {
        (target.module, target.dataset, target.branch, target.stage): target for target in targets
    }
    rows: list[dict[str, Any]] = []

    for fixture in run.fixtures:
        if not fixture.branches:
            status = fixture.capability_status.lower()
            state = status if status in {"failed", "unsupported"} else "failed"
            display = state.upper()
            root_stage = order[0]
            root_reason = fixture.diagnostic or "No supported APB branch"
            details = {
                root_stage: {
                    "state": state,
                    "display": display,
                    "error": root_reason,
                }
            }
            details.update(
                {
                    stage_name: {
                        "state": "unavailable",
                        "display": "",
                    }
                    for stage_name in order[1:]
                }
            )
            row: dict[str, Any] = {
                "module": fixture.repo_name,
                "dataset": fixture.dataset,
                "software": fixture.vendor,
                "level": "Unresolved",
                root_stage: display,
                "_stage_details": details,
            }
            row.update(dict.fromkeys(order[1:], ""))
            rows.append(row)
            continue

        for branch in fixture.branches:
            details: dict[str, dict[str, str]] = {}
            row = {
                "module": fixture.repo_name,
                "dataset": fixture.dataset,
                "software": fixture.vendor,
                "level": "MuData" if branch == MUDATA else branch,
            }
            for stage_name in order:
                target = by_key.get((fixture.repo_name, fixture.dataset, branch, stage_name))
                detail = _stage_detail(
                    target,
                    targets=targets,
                    missing_reason="Stage target unavailable",
                )
                details[stage_name] = detail
                row[stage_name] = detail["display"]
            row["_stage_details"] = details
            rows.append(row)
    return rows


def _capability_status(discovery: capabilities.CapabilityDiscovery) -> str:
    """Return the structured discovery status as a stable lowercase value."""
    status = getattr(discovery, "status", None)
    if status is None:
        return "supported" if discovery.branches else "unsupported"
    value = getattr(status, "value", status)
    return str(value).lower()


def _legacy_run_snapshot(
    registry: list[dict[str, Any]],
    corpus: dict[str, Any],
    targets: list[Target],
    *,
    discover: CapabilityResolver,
) -> RunSnapshot:
    """Adapt the retired corpus mapping for compatibility with non-runtime callers."""
    input_root = Path(corpus["input_root"])
    fixtures: list[ResolvedFixture] = []
    for module, module_config in corpus.get("modules", {}).items():
        annotation = module_config.get("annotation")
        fasta = module_config.get("fasta")
        for dataset in module_config.get("datasets", []):
            validate_dataset(module, dataset)
            discovery = discover_dataset_branches(
                dataset,
                input_root,
                discover=discover,
            )
            fixtures.append(
                ResolvedFixture(
                    module=module,
                    repo_name=module,
                    intermediate_hash=dataset["name"],
                    dataset=dataset["name"],
                    software=dataset["vendor"],
                    vendor=dataset["vendor"],
                    input_path=_resolve(dataset["input"], input_root),
                    parameter_path=_resolve(dataset["params"], input_root),
                    branches=tuple(discovery.branches),
                    capability_status=_capability_status(discovery),
                    diagnostic=discovery.diagnostic,
                    annotation_path=(
                        _resolve(annotation, input_root) if annotation is not None else None
                    ),
                    fasta_path=(_resolve(fasta, input_root) if fasta is not None else None),
                )
            )
    return RunSnapshot(
        schema_version=RUN_SNAPSHOT_SCHEMA_VERSION,
        run_id="legacy",
        created_at="",
        test_data_root=input_root,
        output_root=Path(corpus["output_root"]),
        registry_digest="",
        apb_version=None,
        fixtures=tuple(fixtures),
        targets=tuple(targets),
    )


def baskets(
    targets: list[Target],
    registry: list[dict[str, Any]],
    problems: dict[tuple[str, str], list[str]] | None = None,
) -> dict[str, list[dict[str, Any]]]:
    """Group DATASETS into kanban baskets (decision 10, §8).

    A dataset's basket is the furthest stage whose whole prefix (over the dataset's *applicable*
    stages) is done — a CONTIGUOUS prefix, not the bare max-done stage — so a non-contiguous on-disk
    state (a later artifact present while an earlier one is missing) reports the lower basket,
    never a basket whose defining artifact is absent. `next_stage`/`runnable` are per-dataset from
    the dataset's own Target set: `next_stage` is the first not-yet-done applicable stage (or None
    → terminal). Returns an ordered dict keyed by basket label (empty baskets included, for the flow
    strip). Membership is computed only from per-Target output paths, never a filename glob.
    """
    order = stage_order(registry)
    labels = {s["name"]: basket_label(s) for s in registry}
    problems = problems or {}
    result: dict[str, list[dict[str, Any]]] = {b: [] for b in basket_names(registry)}

    by_ds: dict[tuple[str, str, str], list[Target]] = defaultdict(list)
    for t in targets:
        by_ds[(t.module, t.dataset, t.branch)].append(t)

    for (module, dataset, branch), ts in by_ds.items():
        stages_here = {t.stage for t in ts}
        applicable = [s for s in order if s in stages_here]  # this dataset's stages, in topo order
        done = {t.stage: t.output.exists() for t in ts}

        basket_stage: str | None = None
        for stage in applicable:
            if done.get(stage):
                basket_stage = stage
            else:
                break
        next_stage = next((s for s in applicable if not done.get(s)), None)
        basket = INPUTS_BASKET if basket_stage is None else labels[basket_stage]

        result[basket].append(
            {
                "module": module,
                "dataset": dataset,
                "software": ts[0].vendor,
                "level": "MuData" if branch == MUDATA else branch,
                "basket": basket,
                "next_stage": next_stage,
                "runnable": next_stage is not None,
                "problem": "; ".join(problems.get((module, dataset), [])),
            }
        )
    return result


def reject_input_paths(paths: list[Path], input_root: Path | str) -> list[Path]:
    """Return paths outside `input_root`; raise `CleanGuardError` for an input path.

    Resolves both sides, so it also catches relative paths and symlink escapes. This is a **real
    exception**, not an `assert`: `assert` is stripped by `python -O`, and a destructive-action
    guard must never be optimized away.
    """
    in_root = Path(input_root).resolve()
    for p in paths:
        resolved = Path(p).resolve()
        if in_root == resolved or in_root in resolved.parents:
            raise CleanGuardError(f"refusing to clean {p}: it is under input_root {in_root}")
    return paths
